package server

import (
	"embed"
	"io/fs"
	"net/http"
	"strings"

	"ccrouter/internal/gateway"
	"ccrouter/internal/mcp/transport"

	"github.com/gin-gonic/gin"
)

//go:generate sh -c "cd ../../web && npm ci && npm run build"

// distFS holds the compiled admin frontend (embedded from web/dist).
// The web/dist directory is generated by `npm run build` inside web/.
//
// If this file fails to compile with "no matching files", run:
//
//	make web          — build frontend only
//	make build        — build frontend + Go binary
//	go generate ./... — same as `make web`
//
//go:embed all:web/dist
var distFS embed.FS

// Router builds the Gin engine wired to the gateway state.
func Router(state *gateway.State) *gin.Engine {
	r := gin.New()
	// Do not trust any proxies: ClientIP() falls back to RemoteAddr so that the
	// login rate limiter cannot be bypassed with a spoofed X-Forwarded-For header
	// when the server is exposed directly.
	_ = r.SetTrustedProxies(nil)
	r.Use(gin.Recovery())

	// Auth middleware: if general.api_keys is set, require Bearer token.
	authMW := apiKeyAuth(state)

	// ---- Proxy endpoints ----
	proxyGroup := r.Group("/", authMW)
	{
		proxyGroup.POST("/v1/chat/completions", func(c *gin.Context) {
			state.Service().Handle(c.Writer, c.Request, "openai", false)
		})
		proxyGroup.POST("/v1/messages", func(c *gin.Context) {
			state.Service().Handle(c.Writer, c.Request, "anthropic", false)
		})
		proxyGroup.POST("/v1/responses", func(c *gin.Context) {
			state.Service().Handle(c.Writer, c.Request, "openai-responses", false)
		})
		proxyGroup.POST("/v1/images/generations", func(c *gin.Context) {
			state.Service().Handle(c.Writer, c.Request, "openai-images", true)
		})
		proxyGroup.POST("/v1/images/edits", func(c *gin.Context) {
			state.Service().Handle(c.Writer, c.Request, "openai-image-edits", true)
		})
		proxyGroup.POST("/v1/embeddings", func(c *gin.Context) {
			state.Service().Handle(c.Writer, c.Request, "openai-embeddings", true)
		})
		proxyGroup.GET("/v1/models", func(c *gin.Context) {
			listModels(c, state)
		})
		proxyGroup.GET("/health", healthCheck)
		proxyGroup.GET("/keys/status", func(c *gin.Context) {
			keysStatus(c, state)
		})
	}

	// ---- MCP Public OAuth endpoints ----
	r.GET("/mcp/auth/start", func(c *gin.Context) { handleMcpAuthStart(c, state) })
	r.GET("/mcp/auth/callback", func(c *gin.Context) { handleMcpAuthCallback(c, state) })

	// ---- MCP Gateway endpoints ----
	mcpGroup := r.Group("/mcp", authMW)
	{
		mcpGroup.POST("/:combo", func(c *gin.Context) {
			if state.MCP() != nil {
				transport.NewHandler(state.MCP()).HandleHTTP(c)
			} else {
				c.JSON(http.StatusServiceUnavailable, gin.H{"error": "mcp gateway not initialized"})
			}
		})
		mcpGroup.GET("/:combo", func(c *gin.Context) {
			if state.MCP() != nil {
				transport.NewHandler(state.MCP()).HandleMethodNotAllowed(c)
			} else {
				c.JSON(http.StatusServiceUnavailable, gin.H{"error": "mcp gateway not initialized"})
			}
		})
		mcpGroup.DELETE("/:combo", func(c *gin.Context) {
			if state.MCP() != nil {
				transport.NewHandler(state.MCP()).HandleMethodNotAllowed(c)
			} else {
				c.JSON(http.StatusServiceUnavailable, gin.H{"error": "mcp gateway not initialized"})
			}
		})
		mcpGroup.GET("/:combo/sse", func(c *gin.Context) {
			if state.MCP() != nil {
				transport.NewHandler(state.MCP()).HandleSSE(c)
			} else {
				c.JSON(http.StatusServiceUnavailable, gin.H{"error": "mcp gateway not initialized"})
			}
		})
		mcpGroup.POST("/:combo/message", func(c *gin.Context) {
			if state.MCP() != nil {
				transport.NewHandler(state.MCP()).HandleMessage(c)
			} else {
				c.JSON(http.StatusServiceUnavailable, gin.H{"error": "mcp gateway not initialized"})
			}
		})
	}

	// ---- Admin API ----
	admin := r.Group("/admin/api", func(c *gin.Context) { c.Set("state", state) })
	{
		// Public auth endpoints
		admin.GET("/auth/status", getAuthStatus)
		admin.POST("/auth/login", adminLogin)
		admin.POST("/auth/logout", adminLogout)

		// Protected admin endpoints
		protected := admin.Group("", adminAuth(state))
		{
			protected.GET("/config", getConfig)
			protected.PUT("/config", putConfig)
			protected.PATCH("/config", patchConfig)
			protected.GET("/config/common", getCommonConfig)
			protected.PUT("/config/common", putCommonConfig)
			protected.GET("/config/model", getModelConfig)
			protected.PUT("/config/model", putModelConfig)
			protected.GET("/config/mcp", getMcpConfig)
			protected.PUT("/config/mcp", putMcpConfig)
			protected.GET("/stats/keys", statsKeys)
			protected.GET("/stats/summary", statsSummary)
			protected.GET("/stats/trend", statsTrend)
			protected.GET("/requests", listRequests)
			protected.GET("/info", adminInfo)
			protected.GET("/health", adminHealth)
			protected.GET("/logs", listLogs)
			protected.GET("/logs/detail/:ts", getLogDetail)
			protected.GET("/logs/settings", getLogSettings)
			protected.PUT("/logs/settings", putLogSettings)
			protected.GET("/mcp/providers", listMcpProviders)
			protected.POST("/mcp/providers/test", testMcpProvider)
			protected.GET("/mcp/providers/:name/capabilities", getMcpProviderCapabilities)
			protected.GET("/mcp/combos", listMcpCombos)
			protected.GET("/mcp/combos/:name/tools", getMcpComboTools)
			protected.POST("/mcp/combos/call", testMcpComboCall)
			protected.GET("/mcp/tokens", listMcpTokens)
			protected.DELETE("/mcp/tokens/:id", deleteMcpToken)
			protected.GET("/mcp/info", adminMcpInfo)
			protected.GET("/mcp/requests", listMcpRequests)
			protected.GET("/mcp/stats/summary", getMcpStatsSummary)
			protected.GET("/mcp/stats/trend", getMcpStatsTrend)
		}
	}

	// ---- Admin SPA (static) ----
	r.NoRoute(func(c *gin.Context) {
		if c.Request.URL.Path == "/admin" || hasPrefix(c.Request.URL.Path, "/admin/") {
			if !matchesStaticAsset(c.Request.URL.Path) {
				// deep-link SPA path → serve index
				c.Request.URL.Path = "/"
				c.Set("spa", true)
				serveSPA(c)
				return
			}
			serveSPA(c)
			return
		}
		c.JSON(http.StatusNotFound, gin.H{"error": "not found"})
	})

	return r
}

// apiKeyAuth returns a middleware that validates the client's credentials
// against general.api_keys. If no api_keys are configured, all requests are
// allowed. Accepts both "Authorization: Bearer <key>" (OpenAI style) and
// "x-api-key: <key>" (Anthropic style). If the client sends only one of the
// two, that one must match a configured key. If the client sends both, both
// must independently match a configured key — a stray/incorrect value in
// either header is rejected, rather than silently ignored.
func apiKeyAuth(state *gateway.State) gin.HandlerFunc {
	return func(c *gin.Context) {
		svc := state.Service()
		keys := svc.Config.General.APIKeys
		if len(keys) == 0 {
			c.Next()
			return
		}

		matches := func(token string) bool {
			for _, k := range keys {
				if k.Key == token {
					return true
				}
			}
			return false
		}

		xAPIKey := c.GetHeader("X-Api-Key")

		var bearerToken string
		hasBearer := false
		if auth := c.GetHeader("Authorization"); auth != "" {
			const prefix = "Bearer "
			if len(auth) > len(prefix) && auth[:len(prefix)] == prefix {
				bearerToken = auth[len(prefix):]
				hasBearer = true
			}
		}

		if xAPIKey == "" && !hasBearer {
			c.AbortWithStatusJSON(http.StatusUnauthorized, gin.H{
				"error": "missing API key (send Authorization: Bearer <key> or X-Api-Key: <key>)",
				"type":  "auth_error",
			})
			return
		}

		if xAPIKey != "" && !matches(xAPIKey) {
			c.AbortWithStatusJSON(http.StatusUnauthorized, gin.H{"error": "invalid API key", "type": "auth_error"})
			return
		}
		if hasBearer && !matches(bearerToken) {
			c.AbortWithStatusJSON(http.StatusUnauthorized, gin.H{"error": "invalid API key", "type": "auth_error"})
			return
		}

		c.Next()
	}
}

func hasPrefix(s, prefix string) bool {
	return len(s) >= len(prefix) && s[:len(prefix)] == prefix
}

// serveSPA serves the embedded admin frontend with SPA fallback to index.html.
func serveSPA(c *gin.Context) {
	sub, err := fs.Sub(distFS, "web/dist")
	if err != nil {
		http.Error(c.Writer, "frontend not loaded", http.StatusInternalServerError)
		return
	}
	path := c.Request.URL.Path
	if path == "/admin" || path == "/admin/" || path == "/" {
		path = "/index.html"
	} else if hasPrefix(path, "/admin/") {
		path = path[len("/admin"):]
	}

	// Serve the requested file if it exists; otherwise fall back to index.html
	// for SPA client-side routing. Reading bytes directly avoids FileServer's
	// automatic directory-redirect behavior.
	name := strings.TrimPrefix(path, "/")
	if _, err := fs.Stat(sub, name); err != nil {
		name = "index.html"
	}
	data, err := fs.ReadFile(sub, name)
	if err != nil {
		http.Error(c.Writer, "frontend not loaded", http.StatusInternalServerError)
		return
	}
	setContentType(c, name)
	c.Writer.WriteHeader(http.StatusOK)
	_, _ = c.Writer.Write(data)
}

func setContentType(c *gin.Context, name string) {
	switch {
	case strings.HasSuffix(name, ".html"):
		c.Header("Content-Type", "text/html; charset=utf-8")
	case strings.HasSuffix(name, ".js"):
		c.Header("Content-Type", "application/javascript")
	case strings.HasSuffix(name, ".css"):
		c.Header("Content-Type", "text/css; charset=utf-8")
	case strings.HasSuffix(name, ".svg"):
		c.Header("Content-Type", "image/svg+xml")
	}
}

// matchesStaticAsset reports whether an /admin/... path looks like an asset
// rather than a client-side route (has a file extension).
func matchesStaticAsset(p string) bool {
	last := p[strings.LastIndex(p, "/")+1:]
	return strings.Contains(last, ".")
}
