package server

import (
	"embed"
	"io/fs"
	"net/http"
	"strings"

	"ccrouter/internal/gateway"

	"github.com/gin-gonic/gin"
)

//go:generate sh -c "cd ../../web && npm ci && npm run build"

// distFS holds the compiled admin frontend (embedded from web/dist).
// The web/dist directory is generated by `npm run build` inside web/.
//
// If this file fails to compile with "no matching files", run:
//
//	make web          — build frontend only
//	make build        — build frontend + Go binary
//	go generate ./... — same as `make web`
//
//go:embed all:web/dist
var distFS embed.FS

// Router builds the Gin engine wired to the gateway state.
func Router(state *gateway.State) *gin.Engine {
	r := gin.New()
	r.Use(gin.Recovery())

	// ---- Proxy endpoints ----
	proxyGroup := r.Group("/")
	{
		proxyGroup.POST("/v1/chat/completions", func(c *gin.Context) {
			state.Service().Handle(c.Writer, c.Request, "openai", false)
		})
		proxyGroup.POST("/v1/messages", func(c *gin.Context) {
			state.Service().Handle(c.Writer, c.Request, "anthropic", false)
		})
		proxyGroup.POST("/v1/responses", func(c *gin.Context) {
			state.Service().Handle(c.Writer, c.Request, "openai-responses", false)
		})
		proxyGroup.POST("/v1/images/generations", func(c *gin.Context) {
			state.Service().Handle(c.Writer, c.Request, "openai-images", true)
		})
		proxyGroup.GET("/v1/models", func(c *gin.Context) {
			listModels(c, state)
		})
		proxyGroup.GET("/health", healthCheck)
		proxyGroup.GET("/keys/status", func(c *gin.Context) {
			keysStatus(c, state)
		})
	}

	// ---- Admin API ----
	admin := r.Group("/admin/api", func(c *gin.Context) { c.Set("state", state) })
	{
		admin.GET("/config", getConfig)
		admin.PUT("/config", putConfig)
		admin.GET("/stats/keys", statsKeys)
		admin.GET("/stats/summary", statsSummary)
		admin.GET("/stats/trend", statsTrend)
		admin.GET("/requests", listRequests)
		admin.GET("/info", adminInfo)
		admin.GET("/health", adminHealth)
		admin.GET("/logs", listLogs)
		admin.GET("/logs/settings", getLogSettings)
		admin.PUT("/logs/settings", putLogSettings)
	}

	// ---- Admin SPA (static) ----
	r.NoRoute(func(c *gin.Context) {
		if c.Request.URL.Path == "/admin" || hasPrefix(c.Request.URL.Path, "/admin/") {
			if !matchesStaticAsset(c.Request.URL.Path) {
				// deep-link SPA path → serve index
				c.Request.URL.Path = "/"
				c.Set("spa", true)
				serveSPA(c)
				return
			}
			serveSPA(c)
			return
		}
		c.JSON(http.StatusNotFound, gin.H{"error": "not found"})
	})

	return r
}

func hasPrefix(s, prefix string) bool {
	return len(s) >= len(prefix) && s[:len(prefix)] == prefix
}

// serveSPA serves the embedded admin frontend with SPA fallback to index.html.
func serveSPA(c *gin.Context) {
	sub, err := fs.Sub(distFS, "web/dist")
	if err != nil {
		http.Error(c.Writer, "frontend not loaded", http.StatusInternalServerError)
		return
	}
	path := c.Request.URL.Path
	if path == "/admin" || path == "/admin/" || path == "/" {
		path = "/index.html"
	} else if hasPrefix(path, "/admin/") {
		path = path[len("/admin"):]
	}

	// Serve the requested file if it exists; otherwise fall back to index.html
	// for SPA client-side routing. Reading bytes directly avoids FileServer's
	// automatic directory-redirect behavior.
	name := strings.TrimPrefix(path, "/")
	if _, err := fs.Stat(sub, name); err != nil {
		name = "index.html"
	}
	data, err := fs.ReadFile(sub, name)
	if err != nil {
		http.Error(c.Writer, "frontend not loaded", http.StatusInternalServerError)
		return
	}
	setContentType(c, name)
	c.Writer.WriteHeader(http.StatusOK)
	_, _ = c.Writer.Write(data)
}

func setContentType(c *gin.Context, name string) {
	switch {
	case strings.HasSuffix(name, ".html"):
		c.Header("Content-Type", "text/html; charset=utf-8")
	case strings.HasSuffix(name, ".js"):
		c.Header("Content-Type", "application/javascript")
	case strings.HasSuffix(name, ".css"):
		c.Header("Content-Type", "text/css; charset=utf-8")
	case strings.HasSuffix(name, ".svg"):
		c.Header("Content-Type", "image/svg+xml")
	}
}

// matchesStaticAsset reports whether an /admin/... path looks like an asset
// rather than a client-side route (has a file extension).
func matchesStaticAsset(p string) bool {
	last := p[strings.LastIndex(p, "/")+1:]
	return strings.Contains(last, ".")
}
